### ISSUE TITLE
Introduce `tsci render image`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/v0.0.x-cli#112]
Can use [tscircuit/soup-to-svg](https://github.com/tscircuit/soup-to-svg)

This feature will enable:

* CI tools to automatically create images of a circuit for READMEs or pull requests
* Regression testing, you can now make sure that no circuits (and therefore their images) are changed accidentally in a way you couldn't identify

### Illustrative Usage

```bash
tsci render image --input ./examples/MyCircuit.tsx --pcb --output MyCircuit.png

tsci render image --input ./examples/MyCircuit.tsx --schematic --output MyCircuit.svg

# renders to ./examples/MyCircuit.png
tsci render image --input ./examples/MyCircuit.tsx --pcb -t png
```

**Comment by imrishabh18** [comment]
@seveibar If I am getting the path to the .tsx file, but that won't return me the soup which I can use for the `circuit-to-png` lib. So, how to approach this to get the soup from a .tsx file, I am confused.

**Comment by seveibar** [comment]
@imrishabh18 there should be a function that converts tsx into soup, i would search for the term "soupify" or follow the codepath for "tsci soupify"
