### ISSUE TITLE
Support `tsci export pnp-csv --input path/to/example.tsx`

### ISSUE THREAD

**Issue by seveibar** [tscircuit/v0.0.x-cli#182]
Should do the same thing as when you hit "File > Export -> Pick'n'Place CSV" from the file menu, but be available from the command line

![image](https://github.com/user-attachments/assets/73485eb5-0888-45ad-a6dd-99158bc6acf7)

**Comment by qalbun-salim** [comment]
Hi @seveibar I am interested in contributing and would like to tackle this issue. Can I work on this as part of hacktoberfest?

**Comment by seveibar** [comment]
@qalbun-salim go for it!

**Comment by qalbun-salim** [comment]
Cool! I'll open the PR tomorrow to be counted as hacktoberfest PR 👍 
Quick question, do you prefer the command to be named as `pnp_csv` or `pnp-csv`?
I saw that one of the existing commands is `export kicad_pcb`, so maybe we want to make it uniform with existing commands (using underscore)
