### ISSUE TITLE
`tsci dev` should increment the port until a port is available

### ISSUE THREAD

**Issue by seveibar** [tscircuit/v0.0.x-cli#30]
Similar to `vite` behavior, if a server is already running just increment the port and try again, repeat until you find a port.

**Comment by seveibar** [comment]
CC @imrishabh18 want to take a look at this one?

**Comment by imrishabh18** [comment]
Okay

**Comment by imrishabh18** [comment]
@DamilolaAlao Actually, I was working on this and almost made the PR. Try from next time picking up issues which are unassigned, so we don't do double work and waste time.
