### ISSUE TITLE
`localhost` IPv4 and IPv6 confusion

### ISSUE THREAD

**Issue by vinceh121** [tscircuit/v0.0.x-cli#47]
Depending on the Node version used (and maybe only on Linux?) the dev server will listen on 127.0.0.1, but the CLI will try to use the API on ::1

I think explicitly using 127.0.0.1 is a good idea for a dev server :)

![screenshot](https://livin-the.astolfo.life/SSHStRv8.png)

**Comment by seveibar** [comment]
Oh interesting thanks for the report! Do you know how I could go about reproducing this? Do you have a workaround?

I'm considering packaging `tsci` as a single binary in the future to give a more consistent user experience (it would bundle bun/node), but until then I should be error'ing out etc.

What node version are you using in that screenshot? `node --version`?

**Comment by vinceh121** [comment]
I think the easiest fix is to set `127.0.0.1` everywhere instead of `localhost`, I don't think there's a feasible workaround other than removing the localhost IPv6 from /etc/hosts.

I'm not sure how you could reproduce it for sure, but I'm running this on Node v18.20.1, the version currently on Debian Testing.

**Comment by seveibar** [comment]
cheers, i'll update to explicitly set 127.0.0.1

**Comment by sarkartanmay393** [comment]
Hi @seveibar  I would like to work on this

**Comment by seveibar** [comment]
🫡
